CREATE TABLE CLIENTE (
  NOME VARCHAR(250) NOT NULL, 
  CPF VARCHAR(11) NOT NULL,
  IDADE NUMBER NOT NULL,
  SEXO VARCHAR(1) NOT NULL,
  INTERESSES VARCHAR(1000) NOT NULL,
  CONSTRAINT CLIENTE_PK PRIMARY KEY (CPF)
  ENABLE
);

CREATE TABLE CONTATO (
  ID NUMBER NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  TELEFONE VARCHAR(11) NOT NULL,
  CLIENTE VARCHAR(11) NOT NULL, 
  CONSTRAINT CONTATO_PK PRIMARY KEY (ID)
  ENABLE
);
  
ALTER TABLE CONTATO ADD FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(CPF);

CREATE SEQUENCE S_CONTATO INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;